import type {
  CharacterEquipmentCatalogEntry,
  CharacterEquipmentSlot,
} from './characterEquipmentTypes';

function slots(...values: CharacterEquipmentSlot[]): CharacterEquipmentSlot[] {
  return values;
}

const CATALOG_ENTRIES: CharacterEquipmentCatalogEntry[] = [
  {
    itemKey: 'iron_sword',
    name: 'Epee de fer simple',
    description: 'Lame polyvalente pour les premiers etages.',
    rarity: 'common',
    compatibleSlots: slots('main_hand'),
    statBonuses: { for: 2, vit: 1 },
    linkedSkill: null,
    buildHint: 'Force / frontal',
  },
  {
    itemKey: 'steel_sword',
    name: 'Lame renforcee',
    description: 'Version plus stable et plus offensive de l epee de base.',
    rarity: 'rare',
    compatibleSlots: slots('main_hand'),
    statBonuses: { for: 3, con: 1, vit: 1 },
    linkedSkill: null,
    buildHint: 'Force / progression',
  },
  {
    itemKey: 'mithril_sword',
    name: 'Lame de mithril',
    description: 'Arme avancee pour les paliers tardifs.',
    rarity: 'epic',
    compatibleSlots: slots('main_hand'),
    statBonuses: { for: 4, dex: 2, vit: 1 },
    linkedSkill: { name: 'Frappe du vanguard', costLabel: 'MP 4' },
    buildHint: 'Force / precision',
  },
  {
    itemKey: 'tower_guard_shield',
    name: 'Bouclier de garde',
    description: 'Bouclier renforce pour tenir les combats de palier.',
    rarity: 'rare',
    compatibleSlots: slots('off_hand'),
    statBonuses: { con: 3, vit: 1 },
    linkedSkill: { name: 'Garde resolue', costLabel: 'Stance' },
    buildHint: 'Defense / robustesse',
  },
  {
    itemKey: 'ember_focus',
    name: 'Catalyseur de braise',
    description: 'Focus de canalisation pour styles techniques.',
    rarity: 'rare',
    compatibleSlots: slots('main_hand', 'off_hand'),
    statBonuses: { int: 4, dex: 1 },
    linkedSkill: { name: 'Braise guidee', costLabel: 'MP 5' },
    buildHint: 'Intelligence / competences',
  },
  {
    itemKey: 'warden_hammer',
    name: 'Marteau de garde',
    description: 'Arme lourde orientee impact.',
    rarity: 'rare',
    compatibleSlots: slots('main_hand'),
    statBonuses: { for: 4, con: 1 },
    linkedSkill: { name: 'Impact frontal', costLabel: 'MP 4' },
    buildHint: 'Force / frontal',
  },
  {
    itemKey: 'reinforced_leather_chest',
    name: 'Plastron de cuir renforce',
    description: 'Piece de torse equilibree pour debut de progression.',
    rarity: 'common',
    compatibleSlots: slots('chest'),
    statBonuses: { con: 2, vit: 1 },
    linkedSkill: null,
    buildHint: 'Equilibre / survie',
  },
  {
    itemKey: 'guard_chestplate',
    name: 'Plastron de garde',
    description: 'Protection frontale pour builds robustes.',
    rarity: 'rare',
    compatibleSlots: slots('chest'),
    statBonuses: { con: 3, for: 1, vit: 1 },
    linkedSkill: null,
    buildHint: 'Defense / frontal',
  },
  {
    itemKey: 'dragon_scale_armor',
    name: 'Armure ecailles draconiques',
    description: 'Armure lourde reservee aux menaces majeures.',
    rarity: 'epic',
    compatibleSlots: slots('chest'),
    statBonuses: { con: 4, for: 2, vit: 1 },
    linkedSkill: { name: 'Peau draconique', costLabel: 'Passif' },
    buildHint: 'Defense / fin MVP',
  },
  {
    itemKey: 'traveler_leggings',
    name: 'Jambieres simples',
    description: 'Piece polyvalente pour garder une bonne tenue.',
    rarity: 'common',
    compatibleSlots: slots('legs'),
    statBonuses: { vit: 2, con: 1 },
    linkedSkill: null,
    buildHint: 'Polyvalence',
  },
  {
    itemKey: 'guard_legplates',
    name: 'Jambieres renforcees',
    description: 'Protection jambes pour build garde.',
    rarity: 'rare',
    compatibleSlots: slots('legs'),
    statBonuses: { con: 2, vit: 1, for: 1 },
    linkedSkill: null,
    buildHint: 'Defense / robustesse',
  },
  {
    itemKey: 'field_boots',
    name: 'Bottes de marche',
    description: 'Bottes fiables pour progression reguliere.',
    rarity: 'common',
    compatibleSlots: slots('boots'),
    statBonuses: { vit: 2, dex: 1 },
    linkedSkill: null,
    buildHint: 'Mobilite / equilibre',
  },
  {
    itemKey: 'leather_boots',
    name: 'Bottes de cuir',
    description: 'Bottes legeres pour garder le rythme.',
    rarity: 'common',
    compatibleSlots: slots('boots'),
    statBonuses: { dex: 1, vit: 2 },
    linkedSkill: null,
    buildHint: 'Dexterite / mobilite',
  },
  {
    itemKey: 'ironbound_boots',
    name: 'Bottes ferrees',
    description: 'Ancrage defensif pour combats exigeants.',
    rarity: 'rare',
    compatibleSlots: slots('boots'),
    statBonuses: { con: 2, vit: 1 },
    linkedSkill: null,
    buildHint: 'Defense / maintien',
  },
  {
    itemKey: 'work_gloves',
    name: 'Gants de travail',
    description: 'Piece utilitaire de depart.',
    rarity: 'common',
    compatibleSlots: slots('gloves'),
    statBonuses: { dex: 1, vit: 1 },
    linkedSkill: null,
    buildHint: 'Polyvalence',
  },
  {
    itemKey: 'guard_gauntlets',
    name: 'Gants de garde',
    description: 'Gants solides pour build frontal.',
    rarity: 'rare',
    compatibleSlots: slots('gloves'),
    statBonuses: { con: 2, for: 1 },
    linkedSkill: null,
    buildHint: 'Force / defense',
  },
  {
    itemKey: 'focus_amulet',
    name: 'Amulette de focalisation',
    description: 'Concentre les techniques a base de mana.',
    rarity: 'rare',
    compatibleSlots: slots('amulet'),
    statBonuses: { int: 3, vit: 1 },
    linkedSkill: { name: 'Focus tactique', costLabel: 'MP -1 sur sort' },
    buildHint: 'Intelligence / techniques',
  },
  {
    itemKey: 'vigor_amulet',
    name: 'Amulette de vigueur',
    description: 'Renforce la stabilite en combat long.',
    rarity: 'common',
    compatibleSlots: slots('amulet'),
    statBonuses: { con: 2, vit: 1 },
    linkedSkill: null,
    buildHint: 'Survie / robustesse',
  },
  {
    itemKey: 'vigor_ring',
    name: 'Bague de vigueur',
    description: 'Soutien simple de survie.',
    rarity: 'common',
    compatibleSlots: slots('ring_left', 'ring_right'),
    statBonuses: { con: 1, vit: 1 },
    linkedSkill: null,
    buildHint: 'Survie',
  },
  {
    itemKey: 'clarity_ring',
    name: 'Bague de concentration',
    description: 'Soutien leger pour builds mana.',
    rarity: 'rare',
    compatibleSlots: slots('ring_left', 'ring_right'),
    statBonuses: { int: 2 },
    linkedSkill: null,
    buildHint: 'Intelligence',
  },
  {
    itemKey: 'precision_ring',
    name: 'Bague de precision',
    description: 'Renforce les profils techniques.',
    rarity: 'rare',
    compatibleSlots: slots('ring_left', 'ring_right'),
    statBonuses: { dex: 2 },
    linkedSkill: null,
    buildHint: 'Dexterite',
  },
  {
    itemKey: 'guard_ring',
    name: 'Bague de garde',
    description: 'Soutien defensif discret.',
    rarity: 'common',
    compatibleSlots: slots('ring_left', 'ring_right'),
    statBonuses: { con: 1 },
    linkedSkill: null,
    buildHint: 'Defense',
  },
  {
    itemKey: 'scout_badge',
    name: 'Insigne eclaireur',
    description: 'Accessoire leger de precision.',
    rarity: 'rare',
    compatibleSlots: slots('ring_left', 'ring_right', 'off_hand'),
    statBonuses: { dex: 2, vit: 1 },
    linkedSkill: null,
    buildHint: 'Dexterite / precision',
  },
  {
    itemKey: 'vanguard_insignia',
    name: 'Insigne avant-garde',
    description: 'Insigne militaire axe maintien offensif.',
    rarity: 'rare',
    compatibleSlots: slots('ring_left', 'ring_right', 'off_hand'),
    statBonuses: { for: 1, con: 1, vit: 1 },
    linkedSkill: { name: 'Ordre d assaut', costLabel: 'Cooldown court' },
    buildHint: 'Force / robustesse',
  },
  {
    itemKey: 'thorn_shard',
    name: 'Eclat d epine',
    description: 'Fragment corrompu utilise comme talisman.',
    rarity: 'rare',
    compatibleSlots: slots('ring_left', 'ring_right', 'amulet'),
    statBonuses: { int: 1, dex: 1, vit: 1 },
    linkedSkill: { name: 'Riposte epineuse', costLabel: 'Reactive' },
    buildHint: 'Hybride / utilitaire',
  },
  {
    itemKey: 'relic_of_unbinding',
    name: 'Relique de deliaison',
    description: 'Relique tardive liee aux seuils de malediction.',
    rarity: 'epic',
    compatibleSlots: slots('helmet', 'amulet', 'off_hand'),
    statBonuses: { int: 3, vit: 2 },
    linkedSkill: { name: 'Brisure du sceau', costLabel: 'MP 6' },
    buildHint: 'Intelligence / fin MVP',
  },
  {
    itemKey: 'curse_heart_shard',
    name: 'Eclat de coeur maudit',
    description: 'Objet clef pouvant alimenter un build hybride.',
    rarity: 'epic',
    compatibleSlots: slots('amulet', 'off_hand', 'ring_left', 'ring_right'),
    statBonuses: { for: 1, int: 2, vit: 2 },
    linkedSkill: { name: 'Pulse maudit', costLabel: 'MP 5' },
    buildHint: 'Hybride / puissant',
  },
  {
    itemKey: 'wooden_armor',
    name: 'Armure de bois',
    description: 'Protection rudimentaire de depart.',
    rarity: 'common',
    compatibleSlots: slots('chest'),
    statBonuses: { con: 1, vit: 1 },
    linkedSkill: null,
    buildHint: 'Depart / survie',
  },
  {
    itemKey: 'tempered_alloy',
    name: 'Alliage tempere',
    description: 'Piece d alliage polyvalente utilisee en equipement avance.',
    rarity: 'rare',
    compatibleSlots: slots('helmet', 'chest', 'legs', 'gloves'),
    statBonuses: { con: 2, for: 1 },
    linkedSkill: null,
    buildHint: 'Defense / progression',
  },
  {
    itemKey: 'warden_ember_plate',
    name: 'Plaque braisee de garde',
    description: 'Piece de garde marquant la montee en puissance.',
    rarity: 'rare',
    compatibleSlots: slots('helmet', 'chest'),
    statBonuses: { con: 2, for: 1, int: 1 },
    linkedSkill: null,
    buildHint: 'Defense / hybride',
  },
];

const CATALOG_BY_ITEM_KEY = new Map(CATALOG_ENTRIES.map((entry) => [entry.itemKey, entry]));

export function getCharacterCatalogEntry(itemKey: string): CharacterEquipmentCatalogEntry | null {
  const normalizedKey = itemKey.trim().toLowerCase();
  return CATALOG_BY_ITEM_KEY.get(normalizedKey) ?? null;
}

export function getCharacterRarityLabel(rarity: 'common' | 'rare' | 'epic'): string {
  if (rarity === 'epic') {
    return 'Epique';
  }
  if (rarity === 'rare') {
    return 'Rare';
  }
  return 'Commun';
}
