type HudBindingTarget = Record<string, unknown>;

type HudBindingSelector = {
  field: string;
  selector: string;
};

const HUD_BINDING_SELECTORS: readonly HudBindingSelector[] = [
  { field: 'hudPanelRoot', selector: '[data-hud="panel"]' },
  { field: 'loginButton', selector: '[data-hud-action="login"]' },
  { field: 'logoutButton', selector: '[data-hud-action="logout"]' },
  { field: 'combatStartButton', selector: '[data-combat-action="start"]' },
  { field: 'combatAttackButton', selector: '[data-combat-action="attack"]' },
  { field: 'combatDefendButton', selector: '[data-combat-action="defend"]' },
  { field: 'combatFireballButton', selector: '[data-combat-action="fireball"]' },
  { field: 'combatMendButton', selector: '[data-combat-action="mend"]' },
  { field: 'combatCleanseButton', selector: '[data-combat-action="cleanse"]' },
  { field: 'combatInterruptButton', selector: '[data-combat-action="interrupt"]' },
  { field: 'combatRallyButton', selector: '[data-combat-action="rally"]' },
  { field: 'combatSunderButton', selector: '[data-combat-action="sunder"]' },
  { field: 'combatForfeitButton', selector: '[data-combat-action="forfeit"]' },
  { field: 'combatActionRootRow', selector: '[data-hud="combatActionRoot"]' },
  { field: 'combatActionSkillsRow', selector: '[data-hud="combatActionSkills"]' },
  { field: 'combatActionItemsRow', selector: '[data-hud="combatActionItems"]' },
  { field: 'combatActionHintValue', selector: '[data-hud="combatActionHint"]' },
  { field: 'combatOpenSkillsButton', selector: '[data-combat-ui-action="open-skills"]' },
  { field: 'combatOpenItemsButton', selector: '[data-combat-ui-action="open-items"]' },
  { field: 'combatLogsList', selector: '[data-hud="combatLogs"]' },
  { field: 'combatStatusBadge', selector: '[data-hud="combatStatus"]' },
  { field: 'combatPanelRoot', selector: '[data-hud="combatPanel"]' },
  { field: 'combatEnemyCard', selector: '[data-hud="combatEnemyCard"]' },
  { field: 'combatThreatValue', selector: '[data-hud="combatThreat"]' },
  { field: 'combatErrorValue', selector: '[data-hud="combatError"]' },
  { field: 'questsSummaryValue', selector: '[data-hud="questsSummary"]' },
  { field: 'questsListRoot', selector: '[data-hud="questsList"]' },
  { field: 'questsErrorValue', selector: '[data-hud="questsError"]' },
  { field: 'blacksmithSummaryValue', selector: '[data-hud="blacksmithSummary"]' },
  { field: 'blacksmithOffersRoot', selector: '[data-hud="blacksmithOffers"]' },
  { field: 'blacksmithErrorValue', selector: '[data-hud="blacksmithError"]' },
  { field: 'villageMarketSummaryValue', selector: '[data-hud="villageMarketSummary"]' },
  { field: 'villageMarketSeedsRoot', selector: '[data-hud="villageMarketSeedOffers"]' },
  { field: 'villageMarketBuybackRoot', selector: '[data-hud="villageMarketBuybackOffers"]' },
  { field: 'villageMarketErrorValue', selector: '[data-hud="villageMarketError"]' },
  { field: 'farmSummaryValue', selector: '[data-hud="farmSummary"]' },
  { field: 'farmStorySummaryValue', selector: '[data-hud="farmStorySummary"]' },
  { field: 'farmStoryNarrativeValue', selector: '[data-hud="farmStoryNarrative"]' },
  { field: 'farmSeedSelect', selector: '[data-hud="farmSeedSelect"]' },
  { field: 'farmSleepButton', selector: '[data-farm-action="sleep"]' },
  { field: 'farmPlotsRoot', selector: '[data-hud="farmPlots"]' },
  { field: 'farmErrorValue', selector: '[data-hud="farmError"]' },
  { field: 'farmContextTitleValue', selector: '[data-hud="farmContextTitle"]' },
  { field: 'farmContextStatusValue', selector: '[data-hud="farmContextStatus"]' },
  { field: 'farmContextFeedbackValue', selector: '[data-hud="farmContextFeedback"]' },
  { field: 'farmContextSeedValue', selector: '[data-hud="farmSeedLabel"]' },
  { field: 'farmContextReadyValue', selector: '[data-hud="farmReadyLabel"]' },
  { field: 'farmContextPlantButton', selector: '[data-hud="farmContextPlant"]' },
  { field: 'farmContextWaterButton', selector: '[data-hud="farmContextWater"]' },
  { field: 'farmContextHarvestButton', selector: '[data-hud="farmContextHarvest"]' },
  { field: 'farmCraftingToggleButton', selector: '[data-farm-action="toggle-craft"]' },
  { field: 'farmGoVillageButton', selector: '[data-farm-action="go-village"]' },
  { field: 'villageObjectiveValue', selector: '[data-hud="villageObjective"]' },
  { field: 'villageContextTitleValue', selector: '[data-hud="villageContextTitle"]' },
  { field: 'villageContextRoleValue', selector: '[data-hud="villageContextRole"]' },
  { field: 'villageContextHintValue', selector: '[data-hud="villageContextHint"]' },
  { field: 'villageContextFeedbackValue', selector: '[data-hud="villageContextFeedback"]' },
  { field: 'villageContextInteractButton', selector: '[data-village-action="interact"]' },
  { field: 'villageContextCycleButton', selector: '[data-village-action="cycle"]' },
  { field: 'villageShopPanelRoot', selector: '[data-hud="villageShopPanel"]' },
  { field: 'villageShopNpcValue', selector: '[data-hud="villageShopNpc"]' },
  { field: 'villageShopTitleValue', selector: '[data-hud="villageShopTitle"]' },
  { field: 'villageShopSummaryValue', selector: '[data-hud="villageShopSummary"]' },
  { field: 'villageShopTabsRoot', selector: '[data-hud="villageShopTabs"]' },
  { field: 'villageShopEntriesRoot', selector: '[data-hud="villageShopEntries"]' },
  { field: 'villageShopDetailNameValue', selector: '[data-hud="villageShopDetailName"]' },
  { field: 'villageShopDetailMetaValue', selector: '[data-hud="villageShopDetailMeta"]' },
  { field: 'villageShopDetailDescriptionValue', selector: '[data-hud="villageShopDetailDescription"]' },
  { field: 'villageShopDetailComparisonValue', selector: '[data-hud="villageShopDetailComparison"]' },
  { field: 'villageShopTransactionValue', selector: '[data-hud="villageShopTransaction"]' },
  { field: 'villageShopConfirmButton', selector: '[data-village-shop-action="confirm"]' },
  { field: 'villageShopTalkButton', selector: '[data-village-shop-action="talk"]' },
  { field: 'villageShopErrorValue', selector: '[data-hud="villageShopError"]' },
  { field: 'farmCraftingPanel', selector: '.hud-farm-crafting' },
  { field: 'farmCraftingSummaryValue', selector: '[data-hud="farmCraftingSummary"]' },
  { field: 'farmCraftingListRoot', selector: '[data-hud="farmCraftingRecipes"]' },
  { field: 'farmCraftingErrorValue', selector: '[data-hud="farmCraftingError"]' },
  { field: 'loopSummaryValue', selector: '[data-hud="loopSummary"]' },
  { field: 'loopStageValue', selector: '[data-hud="loopStage"]' },
  { field: 'loopSuppliesValue', selector: '[data-hud="loopSupplies"]' },
  { field: 'loopPrepValue', selector: '[data-hud="loopPreparation"]' },
  { field: 'loopBlockersValue', selector: '[data-hud="loopBlockers"]' },
  { field: 'loopErrorValue', selector: '[data-hud="loopError"]' },
  { field: 'loopPrepareButton', selector: '[data-loop-action="prepare"]' },
  { field: 'towerStorySummaryValue', selector: '[data-hud="towerStorySummary"]' },
  { field: 'towerStoryNarrativeValue', selector: '[data-hud="towerStoryNarrative"]' },
  { field: 'villageNpcSummaryValue', selector: '[data-hud="villageNpcSummary"]' },
  { field: 'villageNpcMayorValue', selector: '[data-hud="villageNpcMayor"]' },
  { field: 'villageNpcBlacksmithValue', selector: '[data-hud="villageNpcBlacksmith"]' },
  { field: 'villageNpcMerchantValue', selector: '[data-hud="villageNpcMerchant"]' },
  { field: 'villageNpcMayorDialogueValue', selector: '[data-hud="villageNpcMayorDialogue"]' },
  { field: 'villageNpcBlacksmithDialogueValue', selector: '[data-hud="villageNpcBlacksmithDialogue"]' },
  { field: 'villageNpcMerchantDialogueValue', selector: '[data-hud="villageNpcMerchantDialogue"]' },
  { field: 'villageNpcErrorValue', selector: '[data-hud="villageNpcError"]' },
  { field: 'villageNpcTalkMayorButton', selector: '[data-village-npc-action="talk"][data-npc-key="mayor"]' },
  {
    field: 'villageNpcTalkBlacksmithButton',
    selector: '[data-village-npc-action="talk"][data-npc-key="blacksmith"]',
  },
  { field: 'villageNpcTalkMerchantButton', selector: '[data-village-npc-action="talk"][data-npc-key="merchant"]' },
  { field: 'autosaveSummaryValue', selector: '[data-hud="autosaveSummary"]' },
  { field: 'autosaveMetaValue', selector: '[data-hud="autosaveMeta"]' },
  { field: 'autosaveActionsRoot', selector: '[data-hud="autosaveActions"]' },
  { field: 'autosaveErrorValue', selector: '[data-hud="autosaveError"]' },
  { field: 'saveSlotsSummaryValue', selector: '[data-hud="savesSummary"]' },
  { field: 'saveSlotsListRoot', selector: '[data-hud="savesList"]' },
  { field: 'saveSlotsErrorValue', selector: '[data-hud="savesError"]' },
  { field: 'heroProfileSummaryValue', selector: '[data-hud="heroProfileSummary"]' },
  { field: 'heroProfileNameInput', selector: '[data-hud="heroProfileName"]' },
  { field: 'heroProfileAppearanceSelect', selector: '[data-hud="heroProfileAppearance"]' },
  { field: 'heroProfileSaveButton', selector: '[data-profile-action="save"]' },
  { field: 'heroProfileMessageValue', selector: '[data-hud="heroProfileMessage"]' },
  { field: 'heroProfileErrorValue', selector: '[data-hud="heroProfileError"]' },
  { field: 'introSummaryValue', selector: '[data-hud="introSummary"]' },
  { field: 'introNarrativeValue', selector: '[data-hud="introNarrative"]' },
  { field: 'introHintValue', selector: '[data-hud="introHint"]' },
  { field: 'introProgressValue', selector: '[data-hud="introProgress"]' },
  { field: 'introAdvanceButton', selector: '[data-intro-action="advance"]' },
  { field: 'introErrorValue', selector: '[data-hud="introError"]' },
  { field: 'characterToggleButton', selector: '[data-hud="characterToggle"]' },
  { field: 'characterPanelRoot', selector: '[data-hud="characterPanel"]' },
  { field: 'characterIdentityValue', selector: '[data-hud="characterIdentity"]' },
  { field: 'characterSummaryValue', selector: '[data-hud="characterSummary"]' },
  { field: 'characterStatsRoot', selector: '[data-hud="characterStats"]' },
  { field: 'characterSecondaryStatsRoot', selector: '[data-hud="characterSecondaryStats"]' },
  { field: 'characterSlotsRoot', selector: '[data-hud="characterSlots"]' },
  { field: 'characterDetailNameValue', selector: '[data-hud="characterDetailName"]' },
  { field: 'characterDetailMetaValue', selector: '[data-hud="characterDetailMeta"]' },
  { field: 'characterDetailDescriptionValue', selector: '[data-hud="characterDetailDescription"]' },
  { field: 'characterComparisonValue', selector: '[data-hud="characterComparison"]' },
  { field: 'characterBuildValue', selector: '[data-hud="characterBuildSummary"]' },
  { field: 'characterLinkedSkillsRoot', selector: '[data-hud="characterLinkedSkills"]' },
  { field: 'characterInventoryRoot', selector: '[data-hud="characterInventory"]' },
  { field: 'characterRefreshButton', selector: '[data-hud="characterRefresh"]' },
  { field: 'characterUnequipButton', selector: '[data-hud="characterUnequip"]' },
  { field: 'characterErrorValue', selector: '[data-hud="characterError"]' },
  { field: 'debugQaPanelRoot', selector: '.hud-debug-qa' },
  { field: 'debugQaStatusValue', selector: '[data-hud="debugQaStatus"]' },
  { field: 'debugQaMessageValue', selector: '[data-hud="debugQaMessage"]' },
  { field: 'debugQaGrantXpInput', selector: '[data-hud="debugQaXp"]' },
  { field: 'debugQaGrantGoldInput', selector: '[data-hud="debugQaGold"]' },
  { field: 'debugQaTowerFloorInput', selector: '[data-hud="debugQaFloor"]' },
  { field: 'debugQaStatePresetSelect', selector: '[data-hud="debugQaStatePreset"]' },
  { field: 'debugQaQuestKeyInput', selector: '[data-hud="debugQaQuestKey"]' },
  { field: 'debugQaQuestStatusSelect', selector: '[data-hud="debugQaQuestStatus"]' },
  { field: 'debugQaLoadoutPresetSelect', selector: '[data-hud="debugQaLoadout"]' },
  { field: 'debugQaWorldFlagsInput', selector: '[data-hud="debugQaWorldFlags"]' },
  { field: 'debugQaWorldFlagsRemoveInput', selector: '[data-hud="debugQaWorldFlagsRemove"]' },
  { field: 'debugQaWorldFlagsReplaceInput', selector: '[data-hud="debugQaWorldFlagsReplace"]' },
  { field: 'debugQaReplayAutoPlaySpeedSelect', selector: '[data-hud="debugQaReplayAutoPlaySpeed"]' },
  { field: 'debugQaRecapOutcomeFilterSelect', selector: '[data-hud="debugQaRecapOutcomeFilter"]' },
  { field: 'debugQaRecapEnemyFilterInput', selector: '[data-hud="debugQaRecapEnemyFilter"]' },
  { field: 'debugQaStripCalibrationSelect', selector: '[data-hud="debugQaStripCalibrationPreset"]' },
  { field: 'debugQaScriptedIntentsButton', selector: '[data-debug-action="load-scripted-intents"]' },
  { field: 'debugQaScriptedIntentsOutput', selector: '[data-hud="debugQaScriptedIntents"]' },
  { field: 'debugQaScriptEnemyFilterInput', selector: '[data-hud="debugQaScriptEnemyFilter"]' },
  { field: 'debugQaScriptIntentFilterInput', selector: '[data-hud="debugQaScriptIntentFilter"]' },
  { field: 'debugQaGrantButton', selector: '[data-debug-action="grant-resources"]' },
  { field: 'debugQaTowerFloorButton', selector: '[data-debug-action="set-tower-floor"]' },
  { field: 'debugQaStatePresetButton', selector: '[data-debug-action="apply-state-preset"]' },
  { field: 'debugQaSetQuestStatusButton', selector: '[data-debug-action="set-quest-status"]' },
  { field: 'debugQaLoadoutButton', selector: '[data-debug-action="apply-loadout-preset"]' },
  { field: 'debugQaCompleteQuestsButton', selector: '[data-debug-action="complete-quests"]' },
  { field: 'debugQaSetWorldFlagsButton', selector: '[data-debug-action="set-world-flags"]' },
  { field: 'debugQaImportButton', selector: '[data-debug-action="import-trace"]' },
  { field: 'debugQaReplayButton', selector: '[data-debug-action="replay-trace"]' },
  { field: 'debugQaReplayStepStartButton', selector: '[data-debug-action="replay-trace-step-start"]' },
  { field: 'debugQaReplayStepNextButton', selector: '[data-debug-action="replay-trace-step-next"]' },
  { field: 'debugQaReplayAutoPlayButton', selector: '[data-debug-action="replay-trace-step-autoplay"]' },
  { field: 'debugQaReplayStepStopButton', selector: '[data-debug-action="replay-trace-step-stop"]' },
  { field: 'debugQaStripCalibrationButton', selector: '[data-debug-action="apply-strip-calibration"]' },
  { field: 'debugQaImportFileInput', selector: '[data-hud="debugQaImportFile"]' },
  { field: 'debugQaExportButton', selector: '[data-debug-action="export-trace"]' },
  { field: 'debugQaExportMarkdownButton', selector: '[data-debug-action="export-markdown"]' },
];

export function bindHudElements(target: HudBindingTarget, root: ParentNode): void {
  const mutableTarget = target as Record<string, Element | null>;
  for (const binding of HUD_BINDING_SELECTORS) {
    mutableTarget[binding.field] = root.querySelector(binding.selector);
  }
}

export function clearHudElementBindings(target: HudBindingTarget): void {
  const mutableTarget = target as Record<string, null>;
  for (const binding of HUD_BINDING_SELECTORS) {
    mutableTarget[binding.field] = null;
  }
}
